### ISSUE TITLE
Page needs improvement

### ISSUE THREAD

**Issue by mikepc** [knative/docs#1406] opened 2019-05-31 16:47 UTC
## Expected Behavior
The link:
https://knative.dev/docs/serving/samples/source-to-url-go
Should respond with content.

## Actual Behavior
Page 404's

## Steps to Reproduce the Problem

1. Point browser at https://knative.dev/docs/build/samples/
2. Click the link "Learn how to use Knative to build apps from source code and then run those containers."
3. Observe error dialog of page 404'ing

## Additional Info

I believe this example would be very helpful to me as I'm wrapping my head around serverless in k8s.  Excellent idea for a sample, looking forward to the page getting fixed!

**Comment by sebgoa** [comment] 2019-06-02 08:15
This is a duplicate of #1367

**Comment by samodell** [comment] 2019-07-08 23:02
Closing as a duplicate.

**Closed by samodell** 2019-07-08 23:02 UTC
