### ISSUE TITLE
Investigate: alpha CLI flag "--prune" for install upgrade

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#533] opened 2018-11-12 19:10 UTC
## Expected Behavior
Upgrade an existing Knative installation to the latest version without negative affects (ie. no lost configuration changes, or left over unused resource objects).

## Actual Behavior
Can reinstall a component over an existing installation but its been reported that some resources get overwritten (#130) and old resources remain in the cluster.

## Possible upgrade method for investigation:

Its not clear if configured resources will remain but there is an alpha level `--prune` flag that can be used with the `kubectl apply` command that might/should at least remove resources that have changed from an installation that upgrades to a new Knative component.

[kubctl CLI - How to delete objects](https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/#how-to-delete-objects)
Example: `kubectl apply --filename [DIRECTORY_PATH]/release.yaml --prune -l your=label`

[Open kubectl issues](https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+kubectl+apply+prune)

**Comment by rgregg** [comment] 2018-11-12 23:18
Which version of kubectl implements this flag? I didn't see it in my installed version.

**Comment by evankanderson** [comment] 2018-11-13 00:14
I have `--prune` as part of `kubectl apply` in 1.9.7:

```shell
C:\Users\xyz>kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp XXXXXXXX: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

C:\Users\xyz>kubectl apply -h
Apply a configuration to a resource by filename or stdin. The resource name must be specified. This resource will be
created if it doesn't exist yet. To use 'apply', always create the resource initially with either 'apply' or 'create
--save-config'.

JSON and YAML formats are accepted.

Alpha Disclaimer: the --prune functionality is not yet complete. Do not use unless you are aware of what the current
state is. See https://issues.k8s.io/34274.

Examples:
  # Apply the configuration in pod.json to a pod.
  kubectl apply -f ./pod.json

  # Apply the JSON passed into stdin to a pod.
  cat pod.json | kubectl apply -f -

  # Note: --prune is still in Alpha
  # Apply the configuration in manifest.yaml that matches label app=nginx and delete all the other resources that are
not in the file and match label app=nginx.
  kubectl apply --prune -f manifest.yaml -l app=nginx

  # Apply the configuration in manifest.yaml and delete all the other configmaps that are not in the file.
  kubectl apply --prune -f manifest.yaml --all --prune-whitelist=core/v1/ConfigMap

Available Commands:
  edit-last-applied Edit latest last-applied-configuration annotations of a resource/object
  set-last-applied  Set the last-applied-configuration annotation on a live object to match the contents of a file.
  view-last-applied View latest last-applied-configuration annotations of a resource/object

Options:
      --all=false: Select all resources in the namespace of the specified resource types.
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in
the template. Only applies to golang and jsonpath output formats.
      --cascade=true: Only relevant during a prune or a force apply. If true, cascade the deletion of the resources
managed by pruned or deleted resources (e.g. Pods created by a ReplicationController).
      --dry-run=false: If true, only print the object that would be sent, without sending it.
  -f, --filename=[]: Filename, directory, or URL to files that contains the configuration to apply
      --force=false: Delete and re-create the specified resource, when PATCH encounters conflict and has retried for 5
times.
      --grace-period=-1: Only relevant during a prune or a force apply. Period of time in seconds given to pruned or
deleted resources to terminate gracefully. Ignored if negative.
      --include-extended-apis=true: If true, include definitions of new APIs via calls to the API server. [default true]
      --include-uninitialized=false: If true, the kubectl command applies to uninitialized objects. If explicitly set to
false, this flag overrides other flags that make the kubectl commands apply to uninitialized objects, e.g., "--all".
Objects with empty metadata.initializers are regarded as initialized.
      --no-headers=false: When using the default or custom-column output format, don't print headers (default print
headers).
      --openapi-patch=true: If true, use openapi to calculate diff when the openapi presents and the resource can be
found in the openapi spec. Otherwise, fall back to use baked-in types.
  -o, --output='': Output format. One of:
json|yaml|wide|name|custom-columns=...|custom-columns-file=...|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...
See custom columns [http://kubernetes.io/docs/user-guide/kubectl-overview/#custom-columns], golang template
[http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template
[http://kubernetes.io/docs/user-guide/jsonpath].
      --overwrite=true: Automatically resolve conflicts between the modified and live configuration by using values from
the modified configuration
      --prune=false: Automatically delete resource objects, including the uninitialized ones, that do not appear in the
configs and are created by either apply or create --save-config. Should be used with either -l or --all.
      --prune-whitelist=[]: Overwrite the default whitelist with <group/version/kind> for --prune
      --record=false: Record current kubectl command in the resource annotation. If set to false, do not record the
command. If set to true, record the command. If not set, default to updating the existing annotation value only if one
already exists.
  -R, --recursive=false: Process the directory used in -f, --filename recursively. Useful when you want to manage
related manifests organized within the same directory.
  -l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='.(e.g. -l key1=value1,key2=value2)
  -a, --show-all=false: When printing, show all resources (default hide terminated pods.)
      --show-labels=false: When printing, show all labels as the last column (default hide labels column)
      --sort-by='': If non-empty, sort list types using this field specification.  The field specification is expressed
as a JSONPath expression (e.g. '{.metadata.name}'). The field in the API resource specified by this JSONPath expression
must be an integer or a string.
      --template='': Template string or path to template file to use when -o=go-template, -o=go-template-file. The
template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
      --timeout=0s: Only relevant during a force apply. The length of time to wait before giving up on a delete of the
old resource, zero means determine a timeout from the size of the object. Any other values should contain a
corresponding time unit (e.g. 1s, 2m, 3h).
      --validate=true: If true, use a schema to validate the input before sending it

Usage:
  kubectl apply -f FILENAME [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by RichieEscarez** [comment] 2019-07-08 23:31
Ping: Has the process for "upgrading" an installation been defined/resolved?

**Comment by RichieEscarez** [comment] 2019-07-09 17:02
Related: https://github.com/knative/serving-operator/issues/59

**Comment by samodell** [comment] 2019-09-03 20:27
Duplicate of #130

**Closed by samodell** 2019-09-03 20:27 UTC
Labels: kind/enhancement, kind/install, kind/question, priority/1, triage/needs-eng-input
