### ISSUE TITLE
istio-pilot horizontal pod autoscaler installed to wrong namespace

### ISSUE THREAD

**Issue by andrewrynhard** [knative/docs#645] opened 2018-12-08 02:05 UTC
## Expected Behavior
`istio-pilot` `HorizontalPodAutoscaler` to be installed in `istio-system`
## Actual Behavior
`istio-pilot` `HorizontalPodAutoscaler` is installed to the current kubeconfig context
## Steps to Reproduce the Problem

1. `kubectl config set-context --current --namespace example`
2. `kubectl apply --filename https://raw.githubusercontent.com/knative/serving/v0.2.2/third_party/istio-1.0.2/istio.yaml`
3. `kubectl get horizontalpodautoscaler`

**Comment by RichieEscarez** [comment] 2018-12-19 01:18
Hi @andrewrynhard, thanks for opening this issue! Can you please help point me to the install guide or page where these steps exist?

**Comment by andrewrynhard** [comment] 2018-12-19 01:32
@RichieEscarez sure thing. I followed the docs here: https://github.com/knative/docs/blob/master/install/Knative-with-any-k8s.md.

**Comment by RichieEscarez** [comment] 2018-12-19 19:47
@mattmoor, using/changing context is new to me but they way I understand it is that if you switch context, then when you run the install command, the installation should occur within that context (specific cluster, user, namespace). 

What I'm confused about here is why the command in the "reproduce" section includes the `--current` flag -> in `kubectl config set-context --current --namespace example` (because it doesnt work for me)?

And, the istio.yaml manifest does specify that the `istio-pilot` `HorizontalPodAutoscaler` should be installed in `istio-system` namespace?

Is there something that we should be mentioning in our installation guides to address the scenario where users install on existing k8s clusters? For example, do we need to include a step for users to create and switch to a new kubectl context before running the installation?

**Comment by evankanderson** [comment] 2018-12-21 22:31
This seems to be a bug in the upstream [`istio/charts/pilot/templates/autoscale.yaml`](http://go/gh/istio/istio/blob/master/install/kubernetes/helm/subcharts/pilot/templates/autoscale.yaml) which doesn't specify a namespace. This seems to have been fixed in https://github.com/istio/istio/pull/7763, but was not included in istio-1.0.2 release.

**Comment by evankanderson** [comment] 2018-12-21 22:34
We can patch this in https://github.com/knative/serving/blob/master/third_party/istio-1.0.2/namespace.yaml.patch and roll it into our next minor release.

**Comment by evankanderson** [comment] 2018-12-21 22:50
This was fixed in https://github.com/knative/serving/pull/2658

**Closed by evankanderson** 2018-12-21 22:50 UTC
Labels: kind/bug, needs eng input
