### ISSUE TITLE
can not pull image due to tls: protocol version not supported

### ISSUE THREAD

**Issue by MatsKeWorks** [knative/docs#5565] opened 2023-05-11 22:00 UTC
## Expected Behavior

I would expect the image to be pulled

Imagepull request is set. Even tried public jfrog to make sure, same error.

## Actual Behavior
```
    Message:                     Revision "some-trigger-service-00011" failed with message: Unable to fetch image "registry.digitalocean.com/something/someimage:latest": failed to resolve image to digest: Get "https://api.digitalocean.com/v2/registry/auth?scope=repository%!A(MISSING)something%!F(MISSING)someimage%!A(MISSING)pull&service=registry.digitalocean.com": remote error: tls: protocol version not supported.
```

## Steps to Reproduce the Problem

1. Create a cluster, possibly with 
2. Install knative
3. Create a service with a random image from a private registry

## Additional Info

I checked out the the tls configuration by using curl to both and checked it with chatgpt.

In the first curl command to ghcr.io, TLSv1.3 with the cipher suite TLS_AES_128_GCM_SHA256 was negotiated, while in the second curl command to registry.digitalocean.com, TLSv1.3 with the cipher suite TLS_AES_256_GCM_SHA384 was negotiated.

The cipher suite TLS_AES_256_GCM_SHA384 provides stronger encryption than TLS_AES_128_GCM_SHA256 due to its use of a larger key size and a more secure hash algorithm. However, both cipher suites are considered to be secure and are widely used by web servers.

**Comment by dprotaso** [comment] 2023-05-12 00:44
Hi - we fixed this in v1.10.1 - https://github.com/knative/serving/releases/tag/knative-v1.10.1

> Install knative

Which Knative instructions were you using?

**Comment by MatsKeWorks** [comment] 2023-05-12 03:11
Thnx! Several to be honest. Including the one from the knative site, but also some less relevant. 

I installed using the digitalocean marketplace installer.

Thnx for coming back to me so fast!

**Comment by dprotaso** [comment] 2023-05-12 14:36
Going to close this out as a dupe of - https://github.com/knative/serving/issues/13937

**Closed by dprotaso** 2023-05-12 14:36 UTC
