### ISSUE TITLE
wrong link/title in api doc

### ISSUE THREAD

**Issue by joshuawilson** [knative/docs#2497] opened 2020-05-22 17:31 UTC
## Expected Behavior
I expected to drill down in the API doc to see that information I was looking for. 

## Actual Behavior
I got a link to a parent of thing that was supposed to be linked to.

## Steps to Reproduce the Problem

1. https://knative.dev/docs/reference/serving-api/#serving.knative.dev/v1.RevisionSpec
2. The `PodSpec` should be `containers`. Containers is a child of PodSpec.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by joshuawilson** [comment] 2020-05-22 18:52
I found another issue just like the described one above.

It should go `service.spec.template` but the docs have `service.spec.ConfigurationSpec.template`

**Comment by sebgoa** [comment] 2020-06-02 08:11
Why do you say that it should not be `PodSpec`, that's what the spec is https://github.com/knative/serving/blob/master/pkg/apis/serving/v1/revision_types.go#L75

Also can you expand on your second comment about `service.spec.template` where do you see that ?

**Comment by joshuawilson** [comment] 2020-06-02 18:29
I talked to @rhuss and he explained that the types are inlined in GoLang and the docs are generated. The inlined type appears in the docs but as a non-GoLang dev I thought something was wrong since the yaml doesn't match. 

At this point, I concede that the docs, spec, and output yaml all match. You can close this if you want. 

However, as a user I find this set up for the docs very confusing. I lost a lot of time trying to match the output yaml with the docs.

**Comment by rhuss** [comment] 2020-06-02 18:33
The misunderstanding is that 

![image](https://user-images.githubusercontent.com/99080/83556161-b4861500-a50f-11ea-8fda-5ae8141abbf9.png)

really is only understandable by Go coders. However, I suppose that the API documentation should be language neutral, ideally something like an OpenAPI schema used by Swagger docs and as used by Kubernetes itself.

Without explaining what "(embedded)" really means in term of the actual YAML resource descriptors or explaining what `int64` is in this context (yaml doesn't really distinguish several integer types) the API documentation as it is is really hard to consume. (and tbh for go-coder reading the source code directly along with the comments there is often easier because accessible directly from the IDE).

Kubernetes itself doesn't use much inlining but what's about having the attributes for the inlined structs be embedded directly in the upper struct, and add some grouping to indicate that a set of attributes belongs to a 'duck type'/partial type/inlined struct ?

Examples would be helpful, too.

**Comment by evankanderson** [comment] 2020-06-02 18:40
@ahmetb is the owner of the tool that does the API documentation generation, IIRC.

Ahmet, are you interested in this bug report? If so, where should it go?

**Comment by ahmetb** [comment] 2020-06-02 20:37
/assign
yeah it's weird containers[] isn't showing up there. will take a look.

**Comment by ahmetb** [comment] 2020-06-02 20:42
@evankanderson actually, there's not much we can do here.

https://github.com/knative/serving/blob/96b5f3e35596e313bc71445abec18d3ba076b9f1/pkg/apis/serving/v1/revision_types.go#L74-L90 shows that there's  `type RevisionSpec { corev1.PodSpec }` embed.

The field name `containers` comes from Kubernetes `corev1.PodSpec`. In v1alpha1 this was working, because we explicitly had a `Container corev1.PodSpec` in RevisionSpec type.

The [Kubernetes corev1.PodSpec type](https://sourcegraph.com/github.com/knative/serving@96b5f3e35596e313bc71445abec18d3ba076b9f1/-/blob/vendor/k8s.io/api/core/v1/types.go#L2833:1) has waaay too many fields, it simply won't work on Knative (and/or fit into our docs page in a neat way when embedded).

So I'm inclined to say we prob. can't fix this in a generic way with the generator (and the problem isn't just `"containers"` field, it's `"volumes"` etc too), maybe we should just fix the godoc on this embed field.

**Comment by abrennan89** [comment] 2020-06-02 22:02
@ahmetb does this issue belong in the docs repo or is it related to something else? Is there any actual documentation requirement here?

**Comment by ahmetb** [comment] 2020-06-02 22:06
Since it’s in the website, let’s keep the issue here. It won’t be a docs fix but the fix would go into this repo.

**Comment by abrennan89** [comment] 2020-06-29 19:41
@ahmetb is there any plan to fix this yet?

**Comment by ahmetb** [comment] 2020-06-29 19:43
I’d say that this is a wontfix. We pretty much never showed the “containers” field’s members and linked to Kubernetes PodSpec page in Kubernetes API Reference. 

Embedding all Kubernetes podspec here won’t be wise bc Knative doesn’t support a good chunk of it.

**Closed** 2020-06-29 19:58 UTC
Labels: kind/bug, kind/not-docs-related, lifecycle/frozen, wontfix
