### ISSUE TITLE
Kubernetes Api Server Source(docs/eventing/samples/kubernetes-event-source/_index.md)

### ISSUE THREAD

**Issue by vaikas-google** [knative/docs#1425] opened 2019-06-06 14:11 UTC
## Expected Behavior
Have links to files or display the files directly

## Actual Behavior
page talks about files but there's (well, at least I couldn't find) no way to actually see the files. 

## Steps to Reproduce the Problem

1. https://knative.dev/docs/eventing/samples/kubernetes-event-source/
1.Look at the Service Account section, it talks about running this command:
kubectl apply --filename serviceaccount.yaml
1. There are additional files referred in that page and it's not very clear where those files are supposed to be at.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by kzjackson1** [comment] 2019-07-09 19:25
I think that this is a duplicate of #1473 (or, rather, that #1473 is a duplicate of this issue). That issue has been resolved, so I'll close this issue.

/close

**Closed by kzjackson1** 2019-07-09 19:25 UTC
