### ISSUE TITLE
Cookies popup keeps coming up

### ISSUE THREAD

**Issue by kmjayadeep** [knative/docs#2009] opened 2019-11-30 01:49 UTC
In documentation website, the popup for the consent of cookies keeps coming up on each page even if we accept it. This behavior greatly deteriorates the user experience.

Steps to reproduce
------
1. go to https://knative.dev/docs/eventing/samples/gcp-pubsub-source/ or any documentation page
2. click on `accept` on cookies prompt
3. refresh page
4. see the popup coming again

Expected behavior
------
The popup should be asked only once per session or for a limited time. It is annoying to click it for each page navigation.

**Comment by RichieEscarez** [comment] 2019-12-07 00:43
Hi @kmjayadeep,

Sorry that you are experiencing an odd behavior on the site. Unfortunately, regardless of the timezone i test, im unable to replicate your issue. The only way I get the "every page cookie notice" behavior is if I turn off/disable cookies in my browser. If your browser is preventing cookies from being stored, then each page load will act as a new request, thus a pop-up for every page. Please let me know if this is not the cause and Ill investigate more.

**Comment by kmjayadeep** [comment] 2019-12-08 05:23
Hi @RichieEscarez 
Thanks for testing it out. It seems like the issue is only in Firefox. I've tried disabling tracking protection and still getting the same result.
however I have observed the following logs in console when i click on accept button
```
UTC time zone within the EU cookie-consent.js:24:13
I consent to the use of cookies on knative.dev cookie-consent.js:36:11
```
I'm not sure why it is showing UTC time zone, as I'm in UTC + 530
Also I don't see anything relevant on cookie tab. I've also tried on incognito mode to make sure that my extensions are not interfering with the cookies, still no luck.

I'll be happy to give any additional details if needed.

**Comment by RichieEscarez** [comment] 2019-12-11 18:45
Thanks for the feedback. It sounds like I need to refine the window for the EU timezone. 

In the meantime, from the Firefox console/terminal, can you run `getcookie()` to  verify that the cookie still exists (you should get `accepted` as the return value)? I might need to do something additional to support that browser (ill try on my end too but I'd like to get another data point to better understand).

ex:
![image](https://user-images.githubusercontent.com/11762685/70649648-7237e700-1c02-11ea-97cd-f4bb2820003e.png)

The popup only looks for the existence of the '`site-cookie`' cookie and if it does not exist, displays the consent dialog.

I appreciate the assistance here, @kmjayadeep!

**Comment by kmjayadeep** [comment] 2019-12-12 05:30
This is what i get in console

```
UTC time zone within the EU cookie-consent.js:24:13
I consent to the use of cookies on knative.dev cookie-consent.js:36:11
getcookie()
"accepted"
```

I tried printing the log before clicking accept button. 
Strange thing is that even though the cookie is there, every time the popup keeps coming.

**Comment by RichieEscarez** [comment] 2019-12-23 22:58
I've tried a few things that I found on the internet to try and resolve the behavior in Firefox but all have failed. Perhaps in the near future a solution will surface? Ill try to swing back around to this and look for other alternatives after i've wrapped up some other priorities.

Thanks again @kmjayadeep!

**Comment by kmjayadeep** [comment] 2019-12-24 01:56
Thanks @RichieEscarez 
I will also try to dig deeper when I get time.

**Comment by RichieEscarez** [comment] 2020-01-06 22:26
@kmjayadeep, this appears to be fixed in https://github.com/knative/website/pull/117. It seems to be working for me in Firefox, can you also validate before we merge in the change?

Here is the staged change: https://deploy-preview-117--knative.netlify.com/

**Comment by kmjayadeep** [comment] 2020-01-07 05:50
Yes the issue seems to be fixed. I have commented in the PR as well.
Great job! Thanks :)

**Comment by RichieEscarez** [comment] 2020-01-07 22:24
https://github.com/knative/website/pull/117 merged, closing

**Closed by RichieEscarez** 2020-01-07 22:24 UTC
Labels: kind/bug, kind/site
