### ISSUE TITLE
Samples reference yaml files that are next to the README file, but no link from website.

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#1324] opened 2019-05-14 21:37 UTC
We should think of a way to get a link to the yaml file referenced from the samples when viewing on the website, at the moment the docs say to apply foo.yaml where foo.yaml is in the same dir as the README.md file but on the knative.dev website it is not discoverable.

**Comment by RichieEscarez** [comment] 2019-05-14 22:39
Duplicate of https://github.com/knative/docs/issues/1045

**Closed by RichieEscarez** 2019-05-14 22:39 UTC
