### ISSUE TITLE
Knative Eventing Sugar Controller(docs/eventing/sugar/_index.md)

### ISSUE THREAD

**Issue by ominiet** [knative/docs#3412] opened 2021-04-02 20:37 UTC
## Expected Behavior

While viewing https://knative.dev/docs/eventing/sugar/#installing 

I expect to see a valid shell snippet for applying the eventing sugar controller resource

## Actual Behavior

What I see is the following snippet instead:

```
kubectl apply --filename {{< artifact repo="eventing" file="eventing-sugar-controller.yaml" >}}
```

**Comment by grantr** [comment] 2021-04-05 19:43
Duplicate of #3236 

#3379 fixes this, and #3417 will backport it to the current release docs.

**Closed by grantr** 2021-04-05 19:43 UTC
Labels: kind/bug
