### ISSUE TITLE
Regarding in-memory-controller in Guide: Getting Started with Eventing

### ISSUE THREAD

**Issue by pajoma** [knative/docs#1927] opened 2019-10-25 07:59 UTC
## Expected Behavior
Output of `kubectl get pods --namespace knative-eventing` after installation of knative eventing resources matches the output in guide. 

```
NAME                                            READY   STATUS    RESTARTS   AGE
eventing-controller-6cdf6ff785-44k98            1/1     Running   0          29m
eventing-webhook-6c4f6699d8-qclbx               1/1     Running   0          29m
imc-controller-85cdb4946b-h2msj                 1/1     Running   0          13m
imc-dispatcher-5f4689d868-fspt6                 1/1     Running   0          13m
in-memory-channel-controller-d9db9d879-f2jw6    1/1     Running   0          13m
in-memory-channel-dispatcher-79bc7f46cd-4mvj6   1/1     Running   0          13m
sources-controller-5847564f4f-z59xc             1/1     Running   0          29m
```

## Actual Behavior
The in-memory controller and dispatcher is missing. 

```
NAME                                  READY   STATUS    RESTARTS   AGE
eventing-controller-db9b58855-xgs56   1/1     Running   0          33s
eventing-webhook-595c6b4fd8-fnznw     1/1     Running   0          33s
imc-controller-7b9b7f9f66-5drbf       1/1     Running   0          32s
imc-dispatcher-775c96b5b5-drdwm       1/1     Running   0          32s
sources-controller-78655cd9f9-hxr6k   1/1     Running   0          33s
```

## Steps to Reproduce the Problem

Install KNative Eventing as described in guide 

It's just confusing, since the output in the guide seems to have two different deployment of the in-memory-channel, the current resource definitions [here](https://github.com/knative/eventing/blob/master/config/channels/in-memory-channel/500-controller.yaml) use "imc" as well.

**Comment by RichieEscarez** [comment] 2019-10-25 20:28
Duplicate of #1926

**Closed by RichieEscarez** 2019-10-25 20:28 UTC
Labels: duplicate, kind/bug, kind/eventing, triage/needs-eng-input
