### ISSUE TITLE
Need to specify branch when cloning repos

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#1320] opened 2019-05-14 19:40 UTC
## Expected Behavior

Clone repo and `kubectl apply` manifest listed in docs should succeed.

Specifically, the autoscale-go example:
https://knative.dev/docs/serving/samples/autoscale-go/

## Actual Behavior

Instructions are to clone the repo, but if we stay on `master` branch we get the v1beta1 API spec of the service which fails if we run a 0.5 cluster.

```
$ kubectl apply -f service.yaml -n sebgoa
Error from server (InternalError): error when creating "service.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "template"
```

That's because we should checkout the 0.5 release branch when we read the 0.5 documentations.

## Steps to Reproduce the Problem

Follow the autoscale-go example.

**Comment by samodell** [comment] 2019-05-14 20:29
Thanks for the write up, @sebgoa !

This is actually a duplicate of #1269 , so I'm going to close this one in favor of that one.

**Closed by samodell** 2019-05-14 20:29 UTC
Labels: kind/bug
