### ISSUE TITLE
code format error when use "

### ISSUE THREAD

**Issue by zgfh** [knative/docs#1509] opened 2019-06-24 04:42 UTC
## Expected Behavior
https://knative.dev/docs/serving/samples/hello-world/helloworld-go/
```
  git clone -b "release-0.6" https://github.com/knative/docs knative-docs

```

## Actual Behavior

```
  git clone -b &#34;release-0.6&#34; https://github.com/knative/docs knative-docs

```

**Comment by samodell** [comment] 2019-06-24 15:32
Thanks for opening this issue, but I'll have to close it out since it's a duplicate of #1472

**Closed by samodell** 2019-06-24 15:32 UTC
Labels: kind/bug
