### ISSUE TITLE
'Hello World - Spring Boot Java' step numbers all render as 1.

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#1482] opened 2019-06-18 15:01 UTC
## Expected Behavior
Steps should display as 1., 2., 3., etc

## Actual Behavior
All steps are rendering on the site as 1. likely due to a formatting issue

## Steps to Reproduce the Problem

1. You can see this present for steps for the tasks in https://knative.dev/v0.4-docs/serving/samples/hello-world/helloworld-java/

**Comment by samodell** [comment] 2019-09-03 20:52
Duplicate of another issue, but we are planning to fix this!

**Closed by samodell** 2019-09-03 20:52 UTC
Labels: kind/bug
