### ISSUE TITLE
(help) Could not resolve host: helloworld-go.default.mydomain.com

### ISSUE THREAD

**Issue by patelrutva** [knative/docs#3313] opened 2021-03-04 23:18 UTC
## Ask your question here:

I am new to knative. I have installed minikube for cluster support and all the required tools for knative . While creating the service in reference of this: [https://knative.dev/docs/serving/getting-started-knative-app/](url)

I am getting below output: 
1) Create service command output as expected):

`kn service create helloworld-go --image gcr.io/knative-samples/helloworld-go --env TARGET="Go Sample v1"`

> Creating service 'helloworld-go' in namespace 'default':
> 
>   0.047s The Configuration is still working to reflect the latest desired specification.
>   0.407s The Route is still working to reflect the latest desired specification.
>   0.522s Configuration "helloworld-go" is waiting for a Revision to become ready.
>  12.683s ...
>  12.882s Ingress has not yet been reconciled.
>  15.143s Ready to serve.
> 
> Service 'helloworld-go' created to latest revision 'helloworld-go-yvtlp-1' is available at URL:
> http://helloworld-go.default.mydomain.com

2) This is my service:

`kn service describe helloworld-go`

> Name:       helloworld-go
> Namespace:  default
> Age:        18s
> URL:        http://helloworld-go.default.mydomain.com
> 
> Revisions:
>   100%  @latest (helloworld-go-yvtlp-1) [1] (18s)
>         Image:  gcr.io/knative-samples/helloworld-go (pinned to 5ea96b)
> 
> Conditions:
>   OK TYPE                   AGE REASON
>   ++ Ready                   3s
>   ++ ConfigurationsReady     5s
>   ++ RoutesReady             3s

3) But when I am trying to curl it's giving me error:

`curl http://helloworld-go.default.mydomain.com -v
`
> * Could not resolve host: helloworld-go.default.mydomain.com
> * Closing connection 0
> curl: (6) Could not resolve host: helloworld-go.default.mydomain.com

Can somebody help?

/help-wanted
/kind/help

**Comment by patelrutva** [comment] 2021-03-04 23:19
help wanted/

**Comment by dprotaso** [comment] 2021-03-06 02:31
/close

dupe of https://github.com/knative/serving/issues/10897

**Closed** 2021-03-06 02:32 UTC
Labels: kind/bug, kind/cli, kind/serving, triage/needs-eng-input
