### ISSUE TITLE
Eventing install does not talk about installing eventing

### ISSUE THREAD

**Issue by matzew** [knative/docs#1189] opened 2019-04-17 16:58 UTC
Looking at v0.4.x:
https://github.com/knative/docs/tree/v0.4.x/docs/eventing#installation

I see actual install scripts for the eventing bits, like:

```
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.4.0/release.yaml
kubectl apply --filename https://github.com/knative/eventing-sources/releases/download/v0.4.0/release.yaml
```

Now, the v0.5.x (and master) completely lacks that section:
https://github.com/knative/docs/tree/v0.5.x/docs/eventing#installation

it just says that eventing requires serving/istio... and no `kubectl` for the actual install

**Comment by samodell** [comment] 2019-04-17 17:07
Dupe of #1174 

@matzew  So this is WAI -- I pulled the install commands off that page since they duplicate the information in the Knative install guides: https://www.knative.dev/docs/install/index.html

That "Installation" header on the Eventing page now links to the install guides, so my hope is that it's easy to find the commands after landing there. The best place to find a list of the current release files is probably https://www.knative.dev/docs/install/knative-custom-install/#choosing-knative-installation-files

My guess is that this issue is mostly popping up because I removed something a few folks seemed to rely on finding in that spot, but I don't think new users would have difficulty navigating to the install from that page. Long-term, it's easier for us to maintain the install instructions in just one place in the docs.

**Closed by samodell** 2019-04-17 17:07 UTC
Labels: duplicate
