### ISSUE TITLE
Copy button for commands to be executed

### ISSUE THREAD

**Issue by dgerd** [knative/docs#1797] opened 2019-09-17 18:53 UTC
**Describe the change you'd like to see**
There are many places in the Knative documentation where a command should be executed. These commands are captured in a formatted code box. However, many of these commands scroll out the side of the frame depending on your browser window size making them hard to copy.

See https://knative.dev/docs/install/knative-with-gke/#installing-knative

It would be nice to have a "select all & copy to clipboard" button to allow me to one click grab the command to run rather than trying to select and highlight manually.

**Comment by RichieEscarez** [comment] 2019-10-15 19:38
Looks like this feature was recently added to the Docsy template. That means we will need to investigate upgrading from our early "beta" version of the docsy code to pick that up.

Marking this a duplicate of https://github.com/knative/website/issues/57

**Closed by RichieEscarez** 2019-10-15 19:38 UTC
Labels: duplicate, kind/site, priority/3
