### ISSUE TITLE
Version Dropdown stutters 

### ISSUE THREAD

**Issue by duglin** [knative/docs#2397] opened 2020-04-15 14:25 UTC
When I go to https://knative.dev/v0.12-docs/  by choosing v0.12 from the version drop-down in the title bar, I see this:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/1944671/79348634-3f309780-7f03-11ea-9246-ec10332017e6.png">

Seems like the "v0.12" shouldn't be repeated

**Comment by mpetason** [comment] 2020-04-28 15:21
There's currently two other issues opened about this:

https://github.com/knative/docs/issues/2328
https://github.com/knative/website/issues/154

**Comment by jonatasbaldin** [comment] 2020-05-06 16:39
Was this fixed? I remember I was able to reproduce it but not anymore 🤔

**Comment by abrennan89** [comment] 2020-06-03 15:39
Seems to be fixed now, can't reproduce for v0.14 docs.

**Closed by abrennan89** 2020-06-03 15:39 UTC
Labels: duplicate, kind/bug
