### ISSUE TITLE
wrong version of kubernetes required when installing knative

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4191] opened 2021-09-07 17:13 UTC
Starting with version 0.24 the minimum version of kubernetes required is 1.19

In the docs today we say the minimum version is 1.18 this is wrong for 0.24, 0.25, and pre-release/main

In addition of `mkdocs` branch we need to update the text in the release branches `release-0.24` and `release-0.25` also.

This is handle by a mkdocs snippet here https://github.com/knative/docs/blob/mkdocs/docs/snippets/prerequisites.md

**Comment by csantanapr** [comment] 2021-09-07 17:15
Here is the source of truth what versions is the minum 
https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-serving-version-table
https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#knative-eventing-version-table

**Comment by snneji** [comment] 2021-09-08 10:08
Hi, I'm going to close as it is a duplicate of https://github.com/knative/docs/issues/4177.

**Closed by snneji** 2021-09-08 10:08 UTC
Labels: kind/bug, kind/good-first-issue, priority/critical
