### ISSUE TITLE
Adding build and eventing installation

### ISSUE THREAD

**Issue by kameshsampath** [knative/docs#904] opened 2019-02-18 04:20 UTC
## What is changing? (Please include as many details as possible.)
Adding Knative build and Knative eventing install to Knative Minikube doc. This helps us to get all Knative component installs in one place. Ref: https://github.com/knative/docs/blob/master/install/Knative-with-GKE.md
## How will this impact our users?
Once place for knative users to look in for install instructions of all documents

If this idea looks good can send in PR

**Comment by RichieEscarez** [comment] 2019-10-02 20:57
Duplicate of https://github.com/knative/docs/issues/1853

**Closed by RichieEscarez** 2019-10-02 20:57 UTC
Labels: kind/install
