### ISSUE TITLE
Installation steps assume knative eventing namespace while it's not there

### ISSUE THREAD

**Issue by konryd** [knative/docs#1028] opened 2019-03-19 11:10 UTC
## Expected Behavior
Installation succeeds when following the installation steps

## Actual Behavior
The installation gets confused by knative eventing.
```
Error from server (NotFound): error when creating "https://github.com/knative/eventing/releases/download/v0.4.0/in-memory-channel.yaml": namespaces "knative-eventing" not found
Error from server (NotFound): error when creating "https://github.com/knative/eventing/releases/download/v0.4.0/in-memory-channel.yaml": namespaces "knative-eventing" not found
Error from server (NotFound): error when creating "https://github.com/knative/eventing/releases/download/v0.4.0/in-memory-channel.yaml": namespaces "knative-eventing" not found
Error from server (NotFound): error when creating "https://github.com/knative/eventing/releases/download/v0.4.0/in-memory-channel.yaml": namespaces "knative-eventing" not found
[unable to recognize "https://github.com/knative/eventing/releases/download/v0.4.0/in-memory-channel.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1", unable to recognize "https://github.com/knative/eventing/releases/download/v0.4.0/in-memory-channel.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1", unable to recognize "https://github.com/knative/eventing/releases/download/v0.4.0/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1", unable to recognize "https://github.com/knative/eventing/releases/download/v0.4.0/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"]
```

## Steps to Reproduce the Problem
1. Create a cluster in GKE using Cloud Console ui (leave everything default)
1. Start following the installation steps from "Grant cluster-admin permissions to the current user:" (inclusive)

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):GKE
 - Knative Version:0.4

**Comment by samodell** [comment] 2019-03-19 23:17
Duplicate of #968 , see that issue for a solution. Docs will be updated soon.

**Closed by samodell** 2019-03-19 23:17 UTC
Labels: duplicate, kind/bug
